<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CryptoScanner.Core</RootNamespace>
    <Configurations>Debug;Release;MaxOS-X-Debug</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CryptoScanner.CoreTests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants)</DefineConstants>
  </PropertyGroup>

	<PropertyGroup>
		<AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
	</PropertyGroup>
	
	<ItemGroup>
    <AvaloniaXaml Remove="Exchange\BloFin\Spot\**" />
    <Compile Remove="Exchange\BloFin\Spot\**" />
    <EmbeddedResource Remove="Exchange\BloFin\Spot\**" />
    <None Remove="Exchange\BloFin\Spot\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Exchange\Binance\Futures\Asset.cs" />
    <Compile Remove="Exchange\Binance\Futures\Order.cs" />
    <Compile Remove="Exchange\Binance\Futures\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Binance\Futures\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Binance\Futures\Trade.cs" />
    <Compile Remove="Exchange\Binance\Spot\Asset.cs" />
    <Compile Remove="Exchange\Binance\Spot\FetchTradesForOrder.cs" />
    <Compile Remove="Exchange\Binance\Spot\Order.cs" />
    <Compile Remove="Exchange\Binance\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Binance\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Binance\Spot\Trade.cs" />
    <Compile Remove="Exchange\BloFin\Spot\Api.cs" />
    <Compile Remove="Exchange\BloFin\Spot\Candle.cs" />
    <Compile Remove="Exchange\BloFin\Spot\Interval.cs" />
    <Compile Remove="Exchange\BloFin\Spot\LimitRate.cs" />
    <Compile Remove="Exchange\BloFin\Spot\SubscriptionKLineTicker.cs" />
    <Compile Remove="Exchange\BloFin\Spot\Symbol.cs" />
    <Compile Remove="Exchange\BybitApi\Futures\Asset.cs" />
    <Compile Remove="Exchange\BybitApi\Futures\FetchTradesForOrder.cs" />
    <Compile Remove="Exchange\BybitApi\Futures\Order.cs" />
    <Compile Remove="Exchange\BybitApi\Futures\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\BybitApi\Futures\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\BybitApi\Futures\Trade.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\Asset.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\CandlesEmulator.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\FetchTradesForOrder.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\Order.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\Trade.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\Asset.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\Order.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\Trade.cs" />
    <Compile Remove="Exchange\Kraken\Spot\Asset.cs" />
    <Compile Remove="Exchange\Kraken\Spot\FetchTradesForOrder.cs" />
    <Compile Remove="Exchange\Kraken\Spot\Order.cs" />
    <Compile Remove="Exchange\Kraken\Spot\SubscriptionKLineTicker - Copy.cs" />
    <Compile Remove="Exchange\Kraken\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Kraken\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Kraken\Spot\Trade.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\Asset.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\Order.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\Trade.cs" />
    <Compile Remove="Exchange\Mexc\Spot\Asset.cs" />
    <Compile Remove="Exchange\Mexc\Spot\Order.cs" />
    <Compile Remove="Exchange\Mexc\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Mexc\Spot\Trade.cs" />
    <Compile Remove="Exchange\Okx\Spot\Asset.cs" />
    <Compile Remove="Exchange\Okx\Spot\Order.cs" />
    <Compile Remove="Exchange\Okx\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Okx\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Okx\Spot\Trade.cs" />
    <Compile Remove="Signal\Other\SignalDoubleTopBottomLong.cs" />
    <Compile Remove="Signal\Other\SignalDoubleTopBottomShort.cs" />
    <Compile Remove="Signal\SignalMacdLtLong.cs" />
    <Compile Remove="Signal\SignalMacdLtShort.cs" />
    <Compile Remove="Signal\SignalMacdTestLong.cs" />
    <Compile Remove="Signal\SignalMacdTestShort .cs" />
    <Compile Remove="Trend\ZigZagIndicator10.cs" />
    <Compile Remove="Trend\ZigZagIndicator11.cs" />
    <Compile Remove="Trend\ZigZagIndicator14.cs" />
    <Compile Remove="Trend\ZigZagIndicator7.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Exchange\Mexc\Spot\SubscriptionKLineTicker - Copy original.cs.txt" />
    <None Remove="Exchange\Mexc\Spot\SubscriptionKLineTicker.old not okay.cs.txt" />
    <None Remove="Exchange\Mexc\Spot\SubscriptionKLineTicker.old okay.cs.txt" />
    <None Remove="Sounds\Old\sound-jump-down.wav" />
    <None Remove="Sounds\Old\sound-jump-up.wav" />
    <None Remove="Sounds\Old\sound-sbm-overbought.wav" />
    <None Remove="Sounds\Old\sound-sbm-oversold.wav" />
    <None Remove="Sounds\Old\sound-stobb-overbought.wav" />
    <None Remove="Sounds\Old\sound-stobb-oversold.wav" />
    <None Remove="Sounds\Old\sound-storsi-overbought.wav" />
    <None Remove="Sounds\Old\sound-storsi-oversold.wav" />
    <None Remove="Sounds\Other\aksu.wav" />
    <None Remove="Sounds\Other\ball_bearing.wav" />
    <None Remove="Sounds\Other\bell_sound.wav" />
    <None Remove="Sounds\Other\boing_sound_effect.wav" />
    <None Remove="Sounds\Other\boxing_bell.wav" />
    <None Remove="Sounds\Other\cool.wav" />
    <None Remove="Sounds\Other\discord_halloween.wav" />
    <None Remove="Sounds\Other\email_entact.wav" />
    <None Remove="Sounds\Other\fade_in.wav" />
    <None Remove="Sounds\Other\huawei.wav" />
    <None Remove="Sounds\Other\la_cucaracha.wav" />
    <None Remove="Sounds\Other\luana.wav" />
    <None Remove="Sounds\Other\mind_transfer_no_jutsu.wav" />
    <None Remove="Sounds\Other\notification.wav" />
    <None Remove="Sounds\Other\popup.wav" />
    <None Remove="Sounds\Other\proxima.wav" />
    <None Remove="Sounds\Other\star_trek_energize.wav" />
    <None Remove="Sounds\Other\suffocation.wav" />
    <None Remove="Sounds\Other\xiaomi_fress.wav" />
    <None Remove="Sounds\sound-dbr-overbought.wav" />
    <None Remove="Sounds\sound-dbr-oversold.wav" />
    <None Remove="Sounds\sound-dlz-overbought.wav" />
    <None Remove="Sounds\sound-dlz-oversold.wav" />
    <None Remove="Sounds\sound-domnear-overbought.wav" />
    <None Remove="Sounds\sound-domnear-oversold.wav" />
    <None Remove="Sounds\sound-domnearby-overbought.wav" />
    <None Remove="Sounds\sound-domnearby-oversold.wav" />
    <None Remove="Sounds\sound-fvg-overbought.wav" />
    <None Remove="Sounds\sound-fvg-oversold.wav" />
    <None Remove="Sounds\sound-heartbeat.wav" />
    <None Remove="Sounds\sound-jump-down.wav" />
    <None Remove="Sounds\sound-jump-up.wav" />
    <None Remove="Sounds\sound-nwe-overbought.wav" />
    <None Remove="Sounds\sound-nwe-oversold.wav" />
    <None Remove="Sounds\sound-sbm-overbought.wav" />
    <None Remove="Sounds\sound-sbm-oversold.wav" />
    <None Remove="Sounds\sound-stobb-overbought.wav" />
    <None Remove="Sounds\sound-stobb-overbought2.wav" />
    <None Remove="Sounds\sound-stobb-oversold.wav" />
    <None Remove="Sounds\sound-stobb-oversold2.wav" />
    <None Remove="Sounds\sound-storsi-overbought.wav" />
    <None Remove="Sounds\sound-storsi-oversold.wav" />
    <None Remove="Sounds\sound-trade-notification.wav" />
    <None Remove="Sounds\sound-trade-notification2.wav" />
    <None Remove="Sounds\sound-uuh-overbought.wav" />
    <None Remove="Sounds\sound-uuh-oversold.wav" />
    <None Remove="Sounds\sound-vbs-overbought.wav" />
    <None Remove="Sounds\sound-vbs-oversold.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Sounds\Old\sound-jump-down.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Old\sound-jump-up.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Old\sound-sbm-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Old\sound-sbm-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Old\sound-stobb-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Old\sound-stobb-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Old\sound-storsi-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Old\sound-storsi-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\aksu.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\ball_bearing.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\bell_sound.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\boing_sound_effect.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\boxing_bell.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\cool.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\discord_halloween.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\email_entact.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\fade_in.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\huawei.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\la_cucaracha.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\luana.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\mind_transfer_no_jutsu.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\notification.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\popup.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\proxima.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\star_trek_energize.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\suffocation.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\Other\xiaomi_fress.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-dbr-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-dbr-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-dlz-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-dlz-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-domnear-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-domnear-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-domnearby-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-domnearby-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-fvg-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-fvg-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-heartbeat.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-jump-down.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-jump-up.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-nwe-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-nwe-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-sbm-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-sbm-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-stobb-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-stobb-overbought2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-stobb-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-stobb-oversold2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-storsi-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-storsi-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-trade-notification.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-trade-notification2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-uuh-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-uuh-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-vbs-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\sound-vbs-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>


  <ItemGroup>
	  <PackageReference Include="Alpaca.Markets" Version="7.2.2" />
	  <PackageReference Include="Avalonia" Version="11.3.18" />
	  <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
	  <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18" />
	  <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	  <PackageReference Include="NAudio" Version="2.3.0" />
	  <PackageReference Include="Binance.Net" Version="13.1.1" />
    <PackageReference Include="BitMart.Net" Version="4.1.1" />
    <PackageReference Include="BloFin.Net" Version="3.1.0" />
    <PackageReference Include="Bybit.Net" Version="7.1.0" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" Version="1.3.8" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="HyperLiquid.Net" Version="5.2.1" />
    <PackageReference Include="JK.Mexc.Net" Version="6.1.1" />
    <PackageReference Include="JK.OKX.Net" Version="5.1.0" />
    <PackageReference Include="JKorf.Coinbase.Net" Version="4.1.0" />
    <PackageReference Include="KrakenExchange.Net" Version="8.1.1" />
    <PackageReference Include="Kucoin.Net" Version="9.1.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="NLog" Version="6.1.4" />
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="Skender.Stock.Indicators" Version="3.0.0-preview.3.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
    <PackageReference Include="Telegram.Bot" Version="19.0.0" />
    <PackageReference Include="Tmds.DBus" Version="0.94.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Sounds\sound-dlz-overbought .wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-fvg-overbought .wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-sbm-overbought2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-sbm-oversold2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-trade-notification-ka-ching.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
