<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BackTest\BackTestData.cs" />
    <Compile Remove="BackTest\BackTestEmulator.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoScanBot.Core\CryptoScanBot.Core.csproj" />
    <ProjectReference Include="..\CryptoScanBot\CryptoScanBot.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="TestForm.cs" />
    <Compile Update="TestForm.Designer.cs">
      <DependentUpon>TestForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="TestForm.resx">
      <DependentUpon>TestForm.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.WindowsDesktop.App" />
	</ItemGroup>
</Project>