<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>CryptoScanner.Config</RootNamespace>
		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>$(DefineConstants)</DefineConstants>
	</PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Avalonia" Version="11.3.17" />
	  <PackageReference Include="Avalonia.Desktop" Version="11.3.17" />
	  <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.17" />
	  <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	  <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.17" />
	  <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.3.17" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
	  <PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.8" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
	  <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoScanner.Core\CryptoScanner.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\ConfigurationWindow.axaml.cs">
      <DependentUpon>ConfigurationWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\StrategyBbmaSettingsView.axaml.cs">
      <DependentUpon>StrategyBbmaSettingsView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
