<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exchange\Bybit\Spot\Candles.cs" />
    <Compile Remove="Exchange\Bybit\Spot\CandlesEmulator.cs" />
    <Compile Remove="Exchange\Bybit\Spot\LimitRates.cs" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="JK.Mexc.Net" Version="3.6.0" />
	  <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoScanBot.Core\CryptoScanBot.Core.csproj" />
  </ItemGroup>

</Project>