using CryptoScanner.Core.Context;
using CryptoScanner.Core.Core;
using CryptoScanner.Core.Enums;
using CryptoScanner.Core.Model;
using CryptoScanner.Core.Trend;

namespace CryptoScanner.CoreTests.Trend;

[TestClass()]
public class ZigZagIndicator9TestsEth : TestBase
{
    // Feeds all 1h ETH candles up to (and including) the given cut-off and returns
    // the settled indicator state.
    private static ZigZagIndicator BuildIndicatorUpTo(
        CryptoCandleList candles,
        DateTime cutOff)
    {
        ZigZagIndicator indicator = new(TrendType.Primary, false);
        foreach (var candle in candles.Values)
        {
            if (candle.Date > cutOff)
                break;
            indicator.Calculate(candle, batchProcess: true);
        }
        indicator.FinishBatch();
        return indicator;
    }

    private static (CryptoSymbol symbol, CryptoCandleList candles) LoadTestData()
    {
        InitTestSession();
        using CryptoDatabase database = new();
        database.Open();

        CryptoSymbol symbol = CreateTestSymbol(database);
        CryptoInterval interval = GlobalData.IntervalListPeriod[CryptoIntervalPeriod.interval1h];
        CryptoSymbolInterval symbolInterval = symbol.GetSymbolInterval(interval.IntervalPeriod);

        string path = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location)
            ?? throw new Exception("Error assembly");
        LoadCandleDataFromDisk(symbolInterval.CandleList, Path.Combine(path, "Trend\\ETHUSDT\\ETHUSDT-1h.json"));

        return (symbol, symbolInterval.CandleList);
    }


    /// <summary>
    /// Run this test once after an algorithm change to print the new expected values.
    /// Copy the output into CalculateTestEthUsdt.
    /// </summary>
    [TestMethod]
    public void DiscoverCheckpointValues()
    {
        var (_, candles) = LoadTestData();

        // Moments in December 2024 where specific ZigZag behaviour was observed.
        DateTime[] dates =
        [
            new(2024, 12, 02, 18, 00, 00, DateTimeKind.Utc),
            new(2024, 12, 03, 06, 00, 00, DateTimeKind.Utc),
            new(2024, 12, 03, 14, 00, 00, DateTimeKind.Utc),
            new(2024, 12, 04, 01, 00, 00, DateTimeKind.Utc),
            new(2024, 12, 04, 14, 00, 00, DateTimeKind.Utc),
            new(2024, 12, 04, 21, 00, 00, DateTimeKind.Utc),
            new(2024, 12, 05, 01, 00, 00, DateTimeKind.Utc),
            new(2024, 12, 05, 03, 00, 00, DateTimeKind.Utc),
            new(2024, 12, 05, 12, 00, 00, DateTimeKind.Utc),
            new(2024, 12, 06, 00, 00, 00, DateTimeKind.Utc),
        ];

        Console.WriteLine("=== Checkpoint discovery — copy into CalculateTestEthUsdt ===");
        Console.WriteLine();
        foreach (var date in dates)
        {
            var ind = BuildIndicatorUpTo(candles, date);
            string low = ind.LastSwingLow?.Candle.Date.ToString("yyyy-MM-dd HH:mm:ss") ?? "null";
            string high = ind.LastSwingHigh?.Candle.Date.ToString("yyyy-MM-dd HH:mm:ss") ?? "null";
            Console.WriteLine($"  At {date:yyyy-MM-dd HH:mm}  ZigZagList={ind.ZigZagList.Count,4}  Low={low}  High={high}");
        }
        Console.WriteLine();
        Console.WriteLine("=== End discovery ===");

        // Always passes — output is used manually to update CalculateTestEthUsdt.
    }


    [TestMethod]
    public void CalculateTestEthUsdt()
    {
        // We noticed ETHUSDT has a strange trend in December 2024 (see picture).
        // Each checkpoint feeds all 1h candles up to that moment and asserts the
        // dates of LastSwingLow and LastSwingHigh as reported by the settled ZigZag.
        //
        // Expected values are generated by DiscoverCheckpointValues — re-run it
        // after any ZigZag / trend-detection refactoring and update the table below.

        var (_, candles) = LoadTestData();

        (DateTime at, DateTime expectedLow, DateTime expectedHigh, string description)[] checkpoints =
        [
            // ── values from DiscoverCheckpointValues (2026-03-22) ────────────────
            (new(2024,12,02,18,00,00,DateTimeKind.Utc), new(2024,12,02,18,00,00,DateTimeKind.Utc), new(2024,12,02,03,00,00,DateTimeKind.Utc), "new swing low, breaks previous box"),
            (new(2024,12,03,06,00,00,DateTimeKind.Utc), new(2024,12,02,18,00,00,DateTimeKind.Utc), new(2024,12,02,16,00,00,DateTimeKind.Utc), "swing high updated to 16:00 candle, low unchanged"),
            (new(2024,12,03,14,00,00,DateTimeKind.Utc), new(2024,12,03,14,00,00,DateTimeKind.Utc), new(2024,12,02,16,00,00,DateTimeKind.Utc), "new swing low at 14:00"),
            (new(2024,12,04,01,00,00,DateTimeKind.Utc), new(2024,12,03,14,00,00,DateTimeKind.Utc), new(2024,12,04,00,00,00,DateTimeKind.Utc), "new swing high (detection lag: pivot at 00:00, detected at 01:00+)"),
            // (it now gets interesting, an ignored point), added a fix because of this, the pivotindex was not properly set because of the reused pount..
            (new(2024,12,04,14,00,00,DateTimeKind.Utc), new(2024,12,03,14,00,00,DateTimeKind.Utc), new(2024,12,04,14,00,00,DateTimeKind.Utc), "repeated high breaks box"),
            (new(2024,12,04,21,00,00,DateTimeKind.Utc), new(2024,12,03,14,00,00,DateTimeKind.Utc), new(2024,12,04,20,00,00,DateTimeKind.Utc), "high updated to 20:00 candle, low unchanged"),
            (new(2024,12,05,01,00,00,DateTimeKind.Utc), new(2024,12,03,14,00,00,DateTimeKind.Utc), new(2024,12,04,21,00,00,DateTimeKind.Utc), "high updated to 21:00 candle, low unchanged"),
            (new(2024,12,05,03,00,00,DateTimeKind.Utc), new(2024,12,03,14,00,00,DateTimeKind.Utc), new(2024,12,04,21,00,00,DateTimeKind.Utc), "no change: neither box broken"),
            (new(2024,12,05,12,00,00,DateTimeKind.Utc), new(2024,12,05,01,00,00,DateTimeKind.Utc), new(2024,12,05,11,00,00,DateTimeKind.Utc), "both swing low and swing high flip"),
            (new(2024,12,06,00,00,00,DateTimeKind.Utc), new(2024,12,06,00,00,00,DateTimeKind.Utc), new(2024,12,05,12,00,00,DateTimeKind.Utc), "new swing low, high remains"),
        ];

        foreach (var (at, expectedLow, expectedHigh, description) in checkpoints)
        {
            var ind = BuildIndicatorUpTo(candles, at);
            Assert.AreEqual(expectedLow, ind.LastSwingLow?.Candle.Date,
                $"LastSwingLow wrong at {at:yyyy-MM-dd HH:mm} — {description}");
            Assert.AreEqual(expectedHigh, ind.LastSwingHigh?.Candle.Date,
                $"LastSwingHigh wrong at {at:yyyy-MM-dd HH:mm} — {description}");
        }
    }
}
