<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exchange\Base\**" />
    <Compile Remove="Exchange\Kucoin\Futures\**" />
    <EmbeddedResource Remove="Exchange\Base\**" />
    <EmbeddedResource Remove="Exchange\Kucoin\Futures\**" />
    <None Remove="Exchange\Base\**" />
    <None Remove="Exchange\Kucoin\Futures\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Exchange\Binance\Futures\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Binance\Futures\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Binance\Spot\FetchTradesForOrder.cs" />
    <Compile Remove="Exchange\Binance\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\BybitApi\Futures\FetchTradesForOrder.cs" />
    <Compile Remove="Exchange\BybitApi\Futures\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\BybitApi\Futures\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\CandlesEmulator.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\FetchTradesForOrder.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\BybitApi\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\Asset.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\Order.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Coinbase\Spot\Trade.cs" />
    <Compile Remove="Exchange\Kraken\Spot\Asset.cs" />
    <Compile Remove="Exchange\Kraken\Spot\FetchTradesForOrder.cs" />
    <Compile Remove="Exchange\Kraken\Spot\Order.cs" />
    <Compile Remove="Exchange\Kraken\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Kraken\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Kraken\Spot\Trade.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\Asset.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\Order.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Kucoin\Spot\Trade.cs" />
    <Compile Remove="Exchange\Mexc\Spot\Asset.cs" />
    <Compile Remove="Exchange\Mexc\Spot\Order.cs" />
    <Compile Remove="Exchange\Mexc\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Mexc\Spot\Trade.cs" />
    <Compile Remove="Exchange\Okx\Spot\Asset.cs" />
    <Compile Remove="Exchange\Okx\Spot\Order.cs" />
    <Compile Remove="Exchange\Okx\Spot\SubscriptionPriceTicker.cs" />
    <Compile Remove="Exchange\Okx\Spot\SubscriptionUserTicker.cs" />
    <Compile Remove="Exchange\Okx\Spot\Trade.cs" />
    <Compile Remove="Signal\Other\SignalDoubleTopBottomLong.cs" />
    <Compile Remove="Signal\Other\SignalDoubleTopBottomShort.cs" />
    <Compile Remove="Signal\SignalMacdLtLong.cs" />
    <Compile Remove="Signal\SignalMacdLtShort.cs" />
    <Compile Remove="Signal\SignalMacdTestLong.cs" />
    <Compile Remove="Signal\SignalMacdTestShort .cs" />
    <Compile Remove="Trend\ZigZagIndicator10.cs" />
    <Compile Remove="Trend\ZigZagIndicator11.cs" />
    <Compile Remove="Trend\ZigZagIndicator14.cs" />
    <Compile Remove="Trend\ZigZagIndicator7.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Exchange\Kucoin\Futures\Interval.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Binance.Net" Version="11.7.0" />
    <PackageReference Include="Bybit.Net" Version="5.8.0" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="JK.Mexc.Net" Version="3.8.0" />
    <PackageReference Include="JK.OKX.Net" Version="3.7.0" />
    <PackageReference Include="JKorf.Coinbase.Net" Version="2.7.0" />
    <PackageReference Include="KrakenExchange.Net" Version="6.7.0" />
    <PackageReference Include="Kucoin.Net" Version="7.7.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
    <PackageReference Include="NLog" Version="6.0.3" />
    <PackageReference Include="NPOI" Version="2.7.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="Skender.Stock.Indicators" Version="2.6.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.8" />
    <PackageReference Include="Telegram.Bot" Version="19.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Sounds\Old\sound-jump-down.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Old\sound-jump-up.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Old\sound-sbm-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Old\sound-sbm-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Old\sound-stobb-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Old\sound-stobb-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Old\sound-storsi-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Old\sound-storsi-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\aksu.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\ball_bearing.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\bell_sound.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\boing_sound_effect.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\boxing_bell.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\cool.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\discord_halloween.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\email_entact.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\fade_in.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\huawei.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\la_cucaracha.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\luana.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\mind_transfer_no_jutsu.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\notification.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\popup.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\proxima.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\star_trek_energize.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\suffocation.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\Other\xiaomi_fress.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-domnear-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-domnear-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-domnearby-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-domnearby-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-heartbeat.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-jump-down.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-jump-up.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-sbm-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-sbm-overbought2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-sbm-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-sbm-oversold2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-stobb-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-stobb-overbought2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-stobb-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-stobb-oversold2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-storsi-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-storsi-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-trade-notification-ka-ching.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-trade-notification.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-trade-notification2.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-uuh-overbought.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\sound-uuh-oversold.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
