<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CryptoScanner.Analyzers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Core" Version="2.1.0" />
    <PackageReference Include="Avalonia" Version="11.3.17" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Skender.Stock.Indicators" Version="3.0.0-preview.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoScanner.Core\CryptoScanner.Core.csproj" />
    <ProjectReference Include="..\CryptoScanner.Config\CryptoScanner.Config.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Sbm\Documentation\" />
    <Folder Include="Stobb\Config\" />
    <Folder Include="Trend\Config\" />
  </ItemGroup>

</Project>
